# Generated by Django 4.2 on 2023-05-02 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UnidadNegocio', '0002_remove_unidadnegocio_direccion_and_more'),
        ('Usuario', '0002_usuario_cedula_usuario_telefono_and_more'),
        ('UnidadProductiva', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadproductiva',
            name='direccion',
        ),
        migrations.AddField(
            model_name='unidadproductiva',
            name='ubcacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='unidadproductiva',
            name='usuarioAuditor',
            field=models.ManyToManyField(blank=True, related_name='user_auditor', to='Usuario.usuario'),
        ),
        migrations.AlterField(
            model_name='unidadproductiva',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='unidadproductiva',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='unidadproductiva',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unidadproductiva',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unidadproductiva',
            name='unidadNegocio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UnidadNegocio.unidadnegocio'),
        ),
    ]
