# Generated by Django 3.1.2 on 2023-05-08 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UnidadProductiva', '0005_auto_20230507_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadproductiva',
            name='unidadNegocio',
        ),
    ]
