# Generated by Django 4.2.1 on 2023-06-14 04:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UnidadProductiva', '0008_remove_unidadproductiva_usuarioregistro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadproductiva',
            name='usuarioConsulta',
            field=models.ManyToManyField(blank=True, related_name='user_consulta', to=settings.AUTH_USER_MODEL),
        ),
    ]
