# Generated by Django 4.2.1 on 2023-06-14 05:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UnidadProductiva', '0009_unidadproductiva_usuarioconsulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadproductiva',
            name='usuarioBancario',
            field=models.ManyToManyField(blank=True, related_name='user_bancario', to=settings.AUTH_USER_MODEL),
        ),
    ]
