# Generated by Django 4.2.1 on 2023-06-21 20:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UnidadProductiva', '0010_unidadproductiva_usuariobancario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadproductiva',
            name='usuarioRegistro',
        ),
        migrations.AddField(
            model_name='unidadproductiva',
            name='usuarioRegistro',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_register', to=settings.AUTH_USER_MODEL),
        ),
    ]
