# Generated by Django 4.2.1 on 2023-06-21 20:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UnidadProductiva', '0011_remove_unidadproductiva_usuarioregistro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadproductiva',
            name='usuarioRegistro',
            field=models.ManyToManyField(blank=True, related_name='user_register', to=settings.AUTH_USER_MODEL),
        ),
    ]
