# Generated by Django 4.2.1 on 2023-05-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0008_usuario_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='last_productiva',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
