# Generated by Django 4.2.1 on 2023-06-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0009_usuario_last_productiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='presupuesto',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
