# Generated by Django 4.2.1 on 2023-06-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0011_alter_usuario_presupuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
