# Generated by Django 4.2 on 2023-04-27 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario', '0001_initial'),
        ('UnidadProductiva', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
                ('monto', models.IntegerField()),
                ('tipo', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=10)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UnidadProductiva.unidadproductiva')),
                ('usuario_reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.usuario')),
            ],
        ),
    ]
