# Generated by Django 4.2 on 2023-04-27 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UnidadNegocio', '0001_initial'),
        ('UnidadProductiva', '0001_initial'),
        ('Movimiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_created=True)),
                ('sub_centro_costo', models.CharField(max_length=50)),
                ('nombre_proveedor', models.CharField(max_length=50)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('numero_documento', models.CharField(max_length=50)),
                ('factura', models.BooleanField(default=False)),
                ('numero_factura', models.CharField(max_length=50)),
                ('concepto', models.FloatField(default=0)),
                ('estado', models.CharField(max_length=10)),
                ('unidad_productiva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UnidadProductiva.unidadproductiva')),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_created=True)),
                ('accion', models.CharField(max_length=20)),
                ('tipo_ingreso', models.CharField(max_length=50)),
                ('valor', models.FloatField(default=0)),
                ('estado', models.CharField(max_length=10)),
                ('unidad_negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UnidadNegocio.unidadnegocio')),
                ('unidad_productiva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UnidadProductiva.unidadproductiva')),
            ],
        ),
        migrations.DeleteModel(
            name='Movimiento',
        ),
    ]
