# Generated by Django 3.1.2 on 2023-05-07 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UnidadProductiva', '0005_auto_20230507_1044'),
        ('Movimiento', '0006_remove_ingreso_sub_centro_costo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_created=True)),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_proveedor', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_centro_costo', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_factura', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('factura', models.BooleanField(blank=True, default=False, null=True)),
                ('estado', models.CharField(blank=True, max_length=10, null=True)),
                ('accion', models.CharField(blank=True, max_length=20, null=True)),
                ('concepto', models.FloatField(default=0)),
                ('valor', models.FloatField(default=0)),
                ('tipo_ingreso', models.CharField(default='IN', max_length=50)),
                ('unidad_productiva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UnidadProductiva.unidadproductiva')),
            ],
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='sub_centro_costo',
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='unidad_negocio',
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='unidad_productiva',
        ),
        migrations.DeleteModel(
            name='Egreso',
        ),
        migrations.DeleteModel(
            name='Ingreso',
        ),
    ]
