# Generated by Django 3.1.2 on 2023-05-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movimiento', '0007_auto_20230507_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='concepto',
            field=models.CharField(max_length=200),
        ),
    ]
