# Generated by Django 3.1.2 on 2023-05-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movimiento', '0008_auto_20230507_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='uuid',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
