# Generated by Django 3.1.2 on 2023-05-07 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CentroCostos', '0005_auto_20230507_1044'),
        ('Movimiento', '0009_movimiento_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='sub_centro_costo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CentroCostos.subcentrocosto'),
        ),
    ]
