# Generated by Django 4.2 on 2023-05-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movimiento', '0011_movimiento_comprobante_factura_alter_movimiento_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='concepto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha_registro',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='valor',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
