# Generated by Django 4.2.1 on 2023-05-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movimiento', '0014_movimiento_comprobante_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='valor',
            field=models.FloatField(default=0),
        ),
    ]
