# Generated by Django 4.2.1 on 2023-05-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movimiento', '0015_alter_movimiento_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='uuid',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
