# Generated by Django 4.2.1 on 2023-05-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movimiento', '0018_movimiento_ingreso_bancario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='uuid',
            field=models.SlugField(blank=True),
        ),
    ]
