# Generated by Django 4.2.1 on 2023-05-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movimiento', '0019_alter_movimiento_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='fecha_aprobacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
