# Generated by Django 4.2.1 on 2023-05-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movimiento', '0020_movimiento_fecha_aprobacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='fecha_aprobacion',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='fecha_modificacion',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
