# Generated by Django 4.2.1 on 2023-05-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movimiento', '0021_remove_movimiento_fecha_aprobacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha_registro',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
