# Generated by Django 4.2.1 on 2023-05-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movimiento', '0023_alter_movimiento_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha_registro',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
