# Generated by Django 4.2.1 on 2023-05-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movimiento', '0024_alter_movimiento_fecha_modificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='accion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
