# Generated by Django 4.2.1 on 2023-06-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movimiento', '0025_alter_movimiento_accion'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='negociacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
