# Generated by Django 4.2.1 on 2023-06-05 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Movimiento', '0026_movimiento_negociacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='usuario_presupuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
