# Generated by Django 4.2.1 on 2023-06-10 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Movimiento', '0028_movimiento_usuario_admin_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='fecha_registro',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
