# Generated by Django 4.2.1 on 2023-08-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movimiento', '0029_alter_movimiento_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='fecha_factura',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
