# Generated by Django 4.2.1 on 2023-08-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movimiento', '0030_movimiento_fecha_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha_registro',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
