# Generated by Django 4.2.1 on 2023-08-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movimiento', '0032_alter_comentario_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='fecha_factura',
            field=models.DateField(blank=True, null=True),
        ),
    ]
