# Generated by Django 4.2.1 on 2024-02-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movimiento', '0033_alter_movimiento_fecha_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='concepto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
