# Generated by Django 4.2.1 on 2024-02-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movimiento', '0034_alter_movimiento_concepto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='concepto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
