# Generated by Django 4.2.1 on 2024-02-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movimiento', '0035_alter_movimiento_concepto'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='concepto_text_field',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='concepto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
