# Generated by Django 4.2.1 on 2024-02-20 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movimiento', '0036_movimiento_concepto_text_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='concepto',
        ),
    ]
