# Generated by Django 4.2 on 2023-05-02 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_usuario_cedula_usuario_telefono_and_more'),
        ('UnidadNegocio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadnegocio',
            name='direccion',
        ),
        migrations.AlterField(
            model_name='unidadnegocio',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuario.usuario'),
        ),
        migrations.AlterField(
            model_name='unidadnegocio',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='unidadnegocio',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='unidadnegocio',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unidadnegocio',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
