# Generated by Django 3.1.2 on 2023-05-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UnidadProductiva', '0006_remove_unidadproductiva_unidadnegocio'),
        ('UnidadNegocio', '0005_auto_20230507_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadnegocio',
            name='unidades_productivas',
            field=models.ManyToManyField(blank=True, null=True, to='UnidadProductiva.UnidadProductiva'),
        ),
    ]
