# Generated by Django 3.1.2 on 2023-05-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UnidadProductiva', '0006_remove_unidadproductiva_unidadnegocio'),
        ('UnidadNegocio', '0006_unidadnegocio_unidades_productivas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadnegocio',
            name='unidades_productivas',
            field=models.ManyToManyField(blank=True, to='UnidadProductiva.UnidadProductiva'),
        ),
    ]
