# Generated by Django 4.2 on 2023-05-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UnidadNegocio', '0002_remove_unidadnegocio_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCentroCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('subcentro', models.ManyToManyField(blank=True, to='CentroCostos.subcentrocosto')),
                ('unegocio', models.ManyToManyField(blank=True, related_name='ccosto_unegocio', to='UnidadNegocio.unidadnegocio')),
            ],
        ),
    ]
