# Generated by Django 4.2 on 2023-05-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentroCostos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrocosto',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subcentrocosto',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
