# Generated by Django 4.2 on 2023-05-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentroCostos', '0005_auto_20230507_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrocosto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subcentrocosto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
